"""fixed oauth model again

Revision ID: f8d1441dd793
Revises: 1ab0e9a7d498
Create Date: 2025-05-21 19:43:52.115350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d1441dd793'
down_revision: Union[str, None] = '1ab0e9a7d498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_account', 'access_token',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.drop_index('ix_oauth_account_account_id', table_name='oauth_account')
    op.drop_index('ix_oauth_account_oauth_name', table_name='oauth_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_oauth_account_oauth_name', 'oauth_account', ['oauth_name'], unique=False)
    op.create_index('ix_oauth_account_account_id', 'oauth_account', ['account_id'], unique=False)
    op.alter_column('oauth_account', 'access_token',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###
